# Boolean arrays

In [4]:
import sys
import numpy as np


In [5]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [13]:
a = np.array([1, 2, 3, 4])

In [14]:
a


array([1, 2, 3, 4])

In [16]:
a[0]

1

In [17]:
a[[True, False, False, True]]

array([1, 4])

In [18]:
a>=1


array([ True,  True,  True,  True])

In [19]:
a>=3

array([False, False,  True,  True])

In [20]:
a[a >=2]

array([2, 3, 4])

In [21]:
A =np.random.randint(100, size=(3, 3))

In [22]:
A

array([[16, 93, 34],
       [ 9, 59, 75],
       [61, 41, 78]])

In [23]:
A>20

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [ ]:
l = 